# Site settings
title: Akande Oluwatosin Adetoye
url: "http://Akande-hub.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: > 
Welcome to my site. I hope you find it exciting!!!
 

# Your information
email: akande.adetoye@aims.ac.rw
author: Akande Oluwatosin Adetoye
avatar: "https://github.com/Akande-hub/Akande-hub.github.io/blob/gh-pages/photos/Akande_face.jpg?raw=true"
profile: Welcome to my site! I hope you find something interesting here.
github_username:  
profile_links:
  Email: "mailto:akande.adetoye@aims.ac.rw"
  GitHub: "https://github.com/Akande-hub"
  Linkedin: "https://linkedin.com/in/tosin-akande-5b3994b9/"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    #Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
